name: Validate Sphinx Documentation

on: [push, pull_request]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install sphinx sphinx-book-theme
    - name: Build Sphinx documentation
      run: |
        sphinx-apidoc -o source/ ../
        cd docs
        make clean
        make html
    - name: Check for uncommitted changes (if there are, it could mean that pre-commit hooks weren't run to build the sphinx documentation)
      run: |
        git status
        if [[ -n $(git status -s) ]]; then
          echo "There are uncommitted changes after building the documentation."
          exit 1
        fi
